### ISSUE TITLE
Implication Unclear

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-building-post-patch-delete-api#2]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208453?module_item_id=480486

### Concern

What exactly are we trying to communicate with this section?

"We all know from experience that we can delete resources on the internet: emails, Instagram posts with unmade beds in the background, etc. Many of these can be performed from the browser, but we don't support them from our API. Why is that?

Browsers are actually very flexible on this front- it's HTML that isn't. The W3C specifications for HTML say that it should only support GET and POST. This means that any requests sent to the API through the browser with unsupported methods will have these methods cast to GET...which will then be used to update and delete resources. (We don't want that!)"

What do we mean that we don't support them from our API? Also, what's the solution to sending non-POST or GET requests? Is it just specifying the request method in the body? Or is it some other technique? 

As of now, it's very unclear what the implications of this information are. It's not clear why this info is relevant to what we're currently doing, nor is it clear how we should resolve the challenges discussed. I think we could either elucidate what we mean more clearly or simply truncate this section.

**Comment by professor-ben** [comment]
Hey Matt,

I just updated the wording in this section. It will be visible in GitHub immediately, but will take about a day to hit Canvas. Please let me know what you think and we can reopen it if necessary.

-Ben

**Comment by Matt-Eva** [comment]
Hey Ben! Thanks for getting back to me. I definitely think this is an improvement.

Students will be familiar with sending HTTP headers from the frontend during fetch requests at this point. Could we drop a sentence in there about that? Such as: 

> We work around these limitations by setting our HTTP method header in our fetch request to methods like 'DELETE' and 'PATCH', as you've seen in phases 1 and 2. However, to make this work the way we want it to, we also need to tell our Flask backend to specifically handle a delete request.

Or something along those lines. I think the current version could still be a little confusing for students who have gone through our curriculum. This will be their first time hearing about HTML's limitations, and they're used to just initiating fetch requests using JavaScript only, which means they're also used to setting method headers for non GET requests. 

This version also still doesn't explicitly state _how_ we work around these HTML limitations. My hypothesis is that it has to do with setting HTTP method headers (as my suggested inclusion indicates), which is also the conclusion that I think students will draw, but it could be helpful to spell that out specifically or clarify if that's not actually the case.

Does that make sense? Hope I'm not being too nit-picky about this.
