### ISSUE TITLE
Will all POST and PATCH requests be accessible with .form?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-building-post-patch-delete-api#3]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208453?module_item_id=480486

### Concern

Text: 

> The request context has access to form data, among many other things. While we haven't created a form here, makeshift forms can still be attached to requests and their attributes can be parsed to create new records.

Will we always write `request.form.get("attribute")` when handling post or patch requests in Flask? This description doesn't really make it clear whether or not this is something we'll always be doing, nor does it describe _how_ this "makeshift form" was attached to the request. Also, what do we mean that we "haven't created a form here"? Is that referring to frontend code or our python code?

I think adding some clarification here could be quite helpful for students. As of now, this description doesn't really explain why we're doing what we're doing in our code, and almost makes it more confusing.

**Comment by professor-ben** [comment]
The short answer here is that it depends heavily on the frontend, and a lot of the frontends set up in the previous curriculum collect and ship data as raw JSON. I think this is worth elaborating on a bit more- I'm going to leave this open to think some more on how to best weave this information into the existing curriculum.

-Ben
