### ISSUE TITLE
Reason for using .filter_by?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-building-post-patch-delete-api#4]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208453?module_item_id=480486

### Concern

In previous lessons / examples, we've used basic `.filter` querying to select a specific resource. However, in this lesson we're choosing to use `.filter_by`, which has slightly different notation. Any particular reason we're choosing to use this here instead of `.filter`? If so, it might be helpful to make a note of it, as it's probably something students will pick up on and have questions about.

**Comment by professor-ben** [comment]
I'm working through this as we speak- `filter_by` allows keyword arguments, which can be convenient but which isn't very extensible or powerful. `filter` is almost always preferred and I'm making an effort to use it wherever possible. I'll change this one now, but other occurrences might be out there. I'm going to get to them all soon!

-Ben
