### ISSUE TITLE
Typo in code example. 

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p4-building-post-patch-delete-api#7]
### Canvas Link

https://learning.flatironschool.com/courses/6267/assignments/236244?module_item_id=554230

### Concern

Section: Handling PATCH Requests, second code example. 

The app route writes the route as '/reviews/<int:id', which is missing its closing angle bracket. 

![image](https://user-images.githubusercontent.com/98498031/230180377-9020997c-59c8-4364-b699-b2826f01696e.png)

### Suggested Changes

'/reviews/<int:id>'

**Comment by pgill97** [comment]
Added missing closing angle bracket.
