### ISSUE TITLE
Unnecessary Line of Code under @app.route('/reviews/<int:id>)

### ISSUE THREAD

**Issue by WAB0003** [learn-co-curriculum/python-p4-building-post-patch-delete-api#8]
### Canvas Link

https://learning.flatironschool.com/courses/6275/assignments/237679?module_item_id=558421

### Concern

Under the _PATCH_ method for this code-along, the review variable is duplicated. Not sure if it really matters but this can be deleted since it's already called at the beginning of _def review_by_id(id)_:

```
@app.route('/reviews/<int:id>', methods=['GET', 'PATCH', 'DELETE'])
def review_by_id(id):
    review = Review.query.filter(Review.id == id).first() <------------LINE ALREADY IN METHOD'S GLOBAL SCOPE

   <-------OTHER CODE FOR GET AND DELETE--------->

        elif request.method == 'PATCH':
            review = Review.query.filter(Review.id == id).first()` #<--THIS LINE IS NOT NEEDED
```

**Comment by professor-ben** [comment]
Thanks for catching this! This is now fixed in the lesson and should be visible on Canvas shortly.

-Ben
